package:
  name: rdma-core-cos7-x86_64
  version: 22.4

source:
  - url: http://mirror.centos.org/centos/7/os/x86_64/Packages/rdma-core-22.4-1.el7.x86_64.rpm
    sha256: e93f70429cb27a7a0850f3e9ea5d9055c16f1bd6a5f06fff7b6b809938994da1
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/rdma-core-22.4-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-64 2.17.*
  run:
    - sysroot_linux-64 2.17.*

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/linux-rdma/rdma-core
  license: GPLv2 or BSD
  license_family: GPL2
  license_file:
    - COPYING.BSD_FB
    - COPYING.BSD_MIT
    - COPYING.GPL2
    - COPYING.md
  summary: (CDT) RDMA core userspace libraries and daemons
  description: |
    RDMA core userspace infrastructure and documentation, including initscripts,
    kernel driver-specific modprobe override configs, IPoIB network scripts,
    dracut rules, and the rdma-ndd utility.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
