package:
  name: libibumad-cos6-x86_64
  version: 1.3.9

source:
  - url: http://mirror.centos.org/centos/6.10/os/x86_64/Packages/libibumad-1.3.9-1.el6.x86_64.rpm
    sha256: 31827ff680757b589eef76c6db1be4d71a21a16c693f40d9f2107d04ca986701
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/6.10/os/Source/SPackages/libibumad-1.3.9-1.el6.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number|int + 1000 }}
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  host:
    - sysroot_linux-64 2.12.*
  run:
    - sysroot_linux-64 2.12.*

test:
  commands:
    - echo "it installs!"

about:
  home: http://openfabrics.org
  license: GPLv2 or BSD
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/libibumad-1.3.9/COPYING
  summary: "(CDT) OpenFabrics Alliance InfiniBand umad (user MAD) library"
  description: |
        libibumad provides the user MAD library functions which sit on top of the user
        MAD modules in the kernel. These are used by the IB diagnostic and management
        tools, including OpenSM.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
