package:
  name: rdma-core-devel-cos7-aarch64
  version: 22.4

source:
  - url: http://mirror.centos.org/altarch/7/os/aarch64/Packages/rdma-core-devel-22.4-1.el7.aarch64.rpm
    sha256: 85bc3f88cc09312442e498ccd39cd76217ab04631ef93d9d2ac7dfd2fd7d7aea
    no_hoist: true
    folder: binary
  # - url: http://vault.centos.org/7.7.1908/os/Source/SPackages/rdma-core-22.4-1.el7.src.rpm
  #   no_hoist: true
  #   folder: source

build:
  number: {{ cdt_build_number }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - ibacm-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
    - libibumad-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
    - libibverbs-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
    - librdmacm-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
    - rdma-core-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
  host:
    - ibacm-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
    - libibumad-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
    - libibverbs-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
    - librdmacm-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
    - rdma-core-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
  run:
    - ibacm-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
    - libibumad-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
    - libibverbs-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
    - librdmacm-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
    - rdma-core-cos7-aarch64 ==22.4 *_{{ cdt_build_number }}
  run_constrained:
    - sysroot_linux-aarch64 ==99999999999

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/linux-rdma/rdma-core
  license: GPLv2 or BSD
  license_family: GPL2
  license_file:
    - COPYING.BSD_FB
    - COPYING.BSD_MIT
    - COPYING.GPL2
    - COPYING.md
  summary: (CDT) RDMA core development libraries and headers
  description: |
    RDMA core development libraries and headers.

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
